### ISSUE TITLE
Model vanishing fix?

### ISSUE THREAD

**Issue by SirCatInaHat** [nlgzrgn/NFSMWExOpts#19] opened 2017-08-17 10:04 UTC
Is there a way of sorting out cars that the bodies disappear  after "X" amount of time then some times resulting in a crash? for me I'm using a Honda Civic that replaces the Fiat Punto, There was a tutorial int ha description of a Youtube video but the link is dead (Including the one in the comments too), I hope you keep updating this mod, The illegal street racing Need for speeds essentially died after Carbon

**Comment by DiamondMaster07** [comment] 2017-08-17 10:08
https://github.com/nlgzrgn/NFSMWExOpts/issues/4

**Comment by nlgzrgn** [comment] 2017-08-20 10:08
Closed: Dupe of #4

**Closed by nlgzrgn** 2017-08-20 10:08 UTC
